CREATE TABLE `SYAIN_MAIN` (
  `SYAIN_ID` int NOT NULL AUTO_INCREMENT,
  `FIRST_NAME_KANJI` varchar(15) COLLATE utf8mb3_unicode_ci NOT NULL,
  `LAST_NAME_KANJI` varchar(15) COLLATE utf8mb3_unicode_ci NOT NULL,
  `FIRST_NAME_KANA` varchar(15) COLLATE utf8mb3_unicode_ci NOT NULL,
  `LAST_NAME_KANA` varchar(15) COLLATE utf8mb3_unicode_ci NOT NULL,
  `FIRST_NAME_EIGO` varchar(15) COLLATE utf8mb3_unicode_ci NOT NULL,
  `LAST_NAME_EIGO` varchar(15) COLLATE utf8mb3_unicode_ci NOT NULL,
  `SEIBETU` int DEFAULT NULL,
  `TANJYOBI` date DEFAULT NULL,
  `KOKUSEKI` int DEFAULT NULL,
  `SYUSSINN` varchar(30) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `HAIGUSYA` int NOT NULL,
  `PASSPORT_NUM` varchar(20) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `PASSPORT_END_DATE` date DEFAULT NULL,
  `VISA_KIKAN` int DEFAULT NULL,
  `VISA_END_DATE` date DEFAULT NULL,
  `ZAIRYU_SIKAKU` int DEFAULT NULL,
  `KOJIN_NUM` varchar(20) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `ZAIRYU_NUM` varchar(20) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `SYOZOKU_KAISYA` int NOT NULL,
  `NYUUSYA_DATE` date DEFAULT NULL,
  `TAISYA_DATE` date DEFAULT NULL,
  `SYOKUGYO_KIND` int NOT NULL,
  `RAINITI_DATE` date DEFAULT NULL,
  `BIKOU` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `YUUBIN` char(8) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `JYUSYO_1` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `JYUSYO_2` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `MOYORI_EKI` varchar(30) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `TEL` varchar(15) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `EMAIL` varchar(50) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `WECHAT` varchar(30) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `LINE` varchar(30) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `BOKOKU_JYUSYO` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `BOKOKU_KINNKYUU_RENNRAKU` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `SAISYUU_GAKUREKI` int NOT NULL,
  `GAKKOU_NAME` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `SENNMOM_NAME` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `SOTUGYO_DATE` date DEFAULT NULL,
  `GYUMU_NENSU` float DEFAULT NULL,
  `IT_OS` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `IT_GENGO` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `IT_DB` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `IT_WEB_SERVER` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `IT_FW` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `IT_OTHER` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `IT_BIKOU` varchar(1024) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `DELETE_FLAG` int NOT NULL,
  `TOUROKUBI` datetime DEFAULT NULL,
  `KOUSINNBI` datetime DEFAULT NULL,
  PRIMARY KEY (`SYAIN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

CREATE TABLE `SYAIN_RIREKI` (
  `SYAIN_ID` int NOT NULL,
  `KAISIBI` date NOT NULL,
  `SYURYOBI` date DEFAULT NULL,
  `KAISYA_NAME` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `BUSYO` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `TOUROKUBI` datetime DEFAULT NULL,
  `KOUSINNBI` datetime DEFAULT NULL,
  `PJ_NAME` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `TAINITI_FLAG` int DEFAULT NULL,
  `BASYO` int DEFAULT NULL,
  `KIBO` int DEFAULT NULL,
  `GYOSYU` int DEFAULT NULL,
  `KAIHATUKANKYO` int DEFAULT NULL,
  `UNYOUKANKYO` int DEFAULT NULL,
  `GENGO` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `DB` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `TOOL` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `TANTOU` int DEFAULT NULL,
  `SAGYOHANI` int DEFAULT NULL,
  `GAIYOU` varchar(1024) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`SYAIN_ID`,`KAISIBI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

create table SYAIN_KEIREKI(
	SYAIN_ID int(11) not null,
	KAISIBI DATE not null,
	SYURYOBI DATE,
	PJ_NAME VARCHAR(100),
	TAINITI_FLAG int(11),
	BASYO int(11),
	KIBO int(11),
	GYOSYU int(11),
	KAIHATUKANKYO int(11),
	UNYOUKANKYO int(11),
	GENGO VARCHAR(100),
	DB VARCHAR(100),
	TOOL VARCHAR(100),
	TANTOU int(11),
	SAGYOHANI int(11),
	GAIYOU VARCHAR(1024),
	TOUROKUBI DATETIME,
	KOUSINNBI DATETIME,
primary key(SYAIN_ID,KAISIBI))
default character set utf8 collate utf8_unicode_ci

CREATE TABLE SYAIN_KYUYO (
  SYAIN_ID INT(11) NOT NULL AUTO_INCREMENT,
  KAISHI_NENGETSU VARCHAR(6) NOT NULL,
  SYURYO_NENGETSU VARCHAR(6) DEFAULT NULL, -- 假设最后的记录可以为 NULL，其他记录不能为 NULL
  KIHONKYU INT(11),
  SYOKUNOUKYU INT(11),
  KOYOU_HOKEN_NO VARCHAR(30),
  NANKIN_NO VARCHAR(30),
  NANKIN_KIJYUN_GAKU INT(11),
  KENKOU_HOKEN_NO VARCHAR(30),
  BIKOU TEXT,
  TOUROKUBI DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 假设登録日是自动创建的
  KOSINNBI DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, -- 假设更新日是自动更新的
  PRIMARY KEY (SYAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SYAIN_KEIHI (
  SYAIN_ID int,
  TEKIYOU_NENGETSU VARCHAR(6),
  RENBAN int,
  HIMOKU int,
  KINGAKU int,
  KYAKUSAKI_SEIKYU_KUBUN int,
  BIKOU VARCHAR(255),
  TOUROKUBI DATETIME,
  KOUSINNBI DATETIME,
  PRIMARY KEY (SYAIN_ID, TEKIYOU_NENGETSU, RENBAN)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE SYAIN_KOUTSUHI (
  SYAIN_ID INT(11) NOT NULL,
  TEKIYOU_NENGETSU VARCHAR(6) NOT NULL,
  RENBAN INT(11) NOT NULL,
  HIMOKU INT(11),
  SYUPPATSU_EKI VARCHAR(30),
  TOUCHAKU_EKI VARCHAR(30),
  KINGAKU INT(11),
  KYAKUSAKI_SEIKYU_KUBUN INT(1), -- 客先請求の有無 0: 無し、1: あり
  BIKOU VARCHAR(255),
  TOUROKUBI DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 自動作成
  KOUSINNBI DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, -- 自動作成
  PRIMARY KEY (SYAIN_ID, TEKIYOU_NENGETSU, RENBAN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `tg_setting` (
  `category1` int NOT NULL,
  `category2` int NOT NULL,
  `category3` int NOT NULL,
  `value1` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `value2` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `value3` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `value4` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `value5` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`category1`,`category2`,`category3`),
  KEY `idx_category1` (`category1`),
  KEY `idx_category2_category3` (`category2`,`category3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `USER_ACCESS_LOG` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `USER_ID` int DEFAULT NULL,
  `GAMEN_ID` varchar(255) DEFAULT NULL,
  `START_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX1` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user_auth` (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `USER_CODE` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `USER_NAME` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PASSWORD` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `USER_ROLE` char(1) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'S:システム管理者 A:統合管理者 B:営業担当 C:経理担当 D:人事担当',
  `IS_YOUKOU` int NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `idx_user_code` (`USER_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

